<?php


/**
 * This class defines the structure of the 'photo_mst' table.
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Mon Jan  4 02:07:59 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PhotoTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PhotoTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('photo_mst');
		$this->setPhpName('Photo');
		$this->setClassname('Photo');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('TITLE', 'Title', 'VARCHAR', true, 255, null);
		$this->addColumn('FILENAME', 'Filename', 'VARCHAR', true, 64, null);
		$this->addColumn('COMMENT', 'Comment', 'VARCHAR', false, 255, null);
		$this->addColumn('WIDTH', 'Width', 'INTEGER', false, null, null);
		$this->addColumn('HEIGHT', 'Height', 'INTEGER', false, null, null);
		$this->addColumn('THUMB_WIDTH', 'ThumbWidth', 'INTEGER', false, null, null);
		$this->addColumn('THUMB_HEIGHT', 'ThumbHeight', 'INTEGER', false, null, null);
		$this->addColumn('ICON_WIDTH', 'IconWidth', 'INTEGER', false, null, null);
		$this->addColumn('ICON_HEIGHT', 'IconHeight', 'INTEGER', false, null, null);
		$this->addColumn('WANDER_WIDTH', 'WanderWidth', 'INTEGER', false, null, null);
		$this->addColumn('WANDER_HEIGHT', 'WanderHeight', 'INTEGER', false, null, null);
		$this->addColumn('SLIDE_WIDTH', 'SlideWidth', 'INTEGER', false, null, null);
		$this->addColumn('SLIDE_HEIGHT', 'SlideHeight', 'INTEGER', false, null, null);
		$this->addColumn('LONGITUDE', 'Longitude', 'DOUBLE', false, null, null);
		$this->addColumn('LATITUDE', 'Latitude', 'DOUBLE', false, null, null);
		$this->addColumn('SHOT_DATE', 'ShotDate', 'TIMESTAMP', false, null, null);
		$this->addColumn('OPEN_DATE', 'OpenDate', 'DATE', false, null, null);
		$this->addColumn('MODIFIED_DATE', 'ModifiedDate', 'TIMESTAMP', false, null, null);
		$this->addColumn('METAMODIFIED_DATE', 'MetamodifiedDate', 'TIMESTAMP', false, null, null);
		$this->addColumn('FILEMTIME', 'Filemtime', 'TIMESTAMP', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // PhotoTableMap
