<?php

/**
 * Base class that represents a row from the 'photo_mst' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Mon Jan  4 02:07:59 2010
 *
 * @package    lib.model.om
 */
abstract class BasePhoto extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PhotoPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the title field.
	 * @var        string
	 */
	protected $title;

	/**
	 * The value for the filename field.
	 * @var        string
	 */
	protected $filename;

	/**
	 * The value for the comment field.
	 * @var        string
	 */
	protected $comment;

	/**
	 * The value for the width field.
	 * @var        int
	 */
	protected $width;

	/**
	 * The value for the height field.
	 * @var        int
	 */
	protected $height;

	/**
	 * The value for the thumb_width field.
	 * @var        int
	 */
	protected $thumb_width;

	/**
	 * The value for the thumb_height field.
	 * @var        int
	 */
	protected $thumb_height;

	/**
	 * The value for the icon_width field.
	 * @var        int
	 */
	protected $icon_width;

	/**
	 * The value for the icon_height field.
	 * @var        int
	 */
	protected $icon_height;

	/**
	 * The value for the wander_width field.
	 * @var        int
	 */
	protected $wander_width;

	/**
	 * The value for the wander_height field.
	 * @var        int
	 */
	protected $wander_height;

	/**
	 * The value for the slide_width field.
	 * @var        int
	 */
	protected $slide_width;

	/**
	 * The value for the slide_height field.
	 * @var        int
	 */
	protected $slide_height;

	/**
	 * The value for the longitude field.
	 * @var        double
	 */
	protected $longitude;

	/**
	 * The value for the latitude field.
	 * @var        double
	 */
	protected $latitude;

	/**
	 * The value for the shot_date field.
	 * @var        string
	 */
	protected $shot_date;

	/**
	 * The value for the open_date field.
	 * @var        string
	 */
	protected $open_date;

	/**
	 * The value for the modified_date field.
	 * @var        string
	 */
	protected $modified_date;

	/**
	 * The value for the metamodified_date field.
	 * @var        string
	 */
	protected $metamodified_date;

	/**
	 * The value for the filemtime field.
	 * @var        string
	 */
	protected $filemtime;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'PhotoPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [title] column value.
	 * 
	 * @return     string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Get the [filename] column value.
	 * 
	 * @return     string
	 */
	public function getFilename()
	{
		return $this->filename;
	}

	/**
	 * Get the [comment] column value.
	 * 
	 * @return     string
	 */
	public function getComment()
	{
		return $this->comment;
	}

	/**
	 * Get the [width] column value.
	 * 
	 * @return     int
	 */
	public function getWidth()
	{
		return $this->width;
	}

	/**
	 * Get the [height] column value.
	 * 
	 * @return     int
	 */
	public function getHeight()
	{
		return $this->height;
	}

	/**
	 * Get the [thumb_width] column value.
	 * 
	 * @return     int
	 */
	public function getThumbWidth()
	{
		return $this->thumb_width;
	}

	/**
	 * Get the [thumb_height] column value.
	 * 
	 * @return     int
	 */
	public function getThumbHeight()
	{
		return $this->thumb_height;
	}

	/**
	 * Get the [icon_width] column value.
	 * 
	 * @return     int
	 */
	public function getIconWidth()
	{
		return $this->icon_width;
	}

	/**
	 * Get the [icon_height] column value.
	 * 
	 * @return     int
	 */
	public function getIconHeight()
	{
		return $this->icon_height;
	}

	/**
	 * Get the [wander_width] column value.
	 * 
	 * @return     int
	 */
	public function getWanderWidth()
	{
		return $this->wander_width;
	}

	/**
	 * Get the [wander_height] column value.
	 * 
	 * @return     int
	 */
	public function getWanderHeight()
	{
		return $this->wander_height;
	}

	/**
	 * Get the [slide_width] column value.
	 * 
	 * @return     int
	 */
	public function getSlideWidth()
	{
		return $this->slide_width;
	}

	/**
	 * Get the [slide_height] column value.
	 * 
	 * @return     int
	 */
	public function getSlideHeight()
	{
		return $this->slide_height;
	}

	/**
	 * Get the [longitude] column value.
	 * 
	 * @return     double
	 */
	public function getLongitude()
	{
		return $this->longitude;
	}

	/**
	 * Get the [latitude] column value.
	 * 
	 * @return     double
	 */
	public function getLatitude()
	{
		return $this->latitude;
	}

	/**
	 * Get the [optionally formatted] temporal [shot_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getShotDate($format = 'Y-m-d H:i:s')
	{
		if ($this->shot_date === null) {
			return null;
		}


		if ($this->shot_date === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->shot_date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->shot_date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [open_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getOpenDate($format = 'Y-m-d')
	{
		if ($this->open_date === null) {
			return null;
		}


		if ($this->open_date === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->open_date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->open_date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [modified_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getModifiedDate($format = 'Y-m-d H:i:s')
	{
		if ($this->modified_date === null) {
			return null;
		}


		if ($this->modified_date === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->modified_date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->modified_date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [metamodified_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getMetamodifiedDate($format = 'Y-m-d H:i:s')
	{
		if ($this->metamodified_date === null) {
			return null;
		}


		if ($this->metamodified_date === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->metamodified_date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->metamodified_date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [filemtime] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFilemtime($format = 'Y-m-d H:i:s')
	{
		if ($this->filemtime === null) {
			return null;
		}


		if ($this->filemtime === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->filemtime);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->filemtime, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = PhotoPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [title] column.
	 * 
	 * @param      string $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title !== $v) {
			$this->title = $v;
			$this->modifiedColumns[] = PhotoPeer::TITLE;
		}

		return $this;
	} // setTitle()

	/**
	 * Set the value of [filename] column.
	 * 
	 * @param      string $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setFilename($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->filename !== $v) {
			$this->filename = $v;
			$this->modifiedColumns[] = PhotoPeer::FILENAME;
		}

		return $this;
	} // setFilename()

	/**
	 * Set the value of [comment] column.
	 * 
	 * @param      string $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setComment($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->comment !== $v) {
			$this->comment = $v;
			$this->modifiedColumns[] = PhotoPeer::COMMENT;
		}

		return $this;
	} // setComment()

	/**
	 * Set the value of [width] column.
	 * 
	 * @param      int $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setWidth($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->width !== $v) {
			$this->width = $v;
			$this->modifiedColumns[] = PhotoPeer::WIDTH;
		}

		return $this;
	} // setWidth()

	/**
	 * Set the value of [height] column.
	 * 
	 * @param      int $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setHeight($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->height !== $v) {
			$this->height = $v;
			$this->modifiedColumns[] = PhotoPeer::HEIGHT;
		}

		return $this;
	} // setHeight()

	/**
	 * Set the value of [thumb_width] column.
	 * 
	 * @param      int $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setThumbWidth($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->thumb_width !== $v) {
			$this->thumb_width = $v;
			$this->modifiedColumns[] = PhotoPeer::THUMB_WIDTH;
		}

		return $this;
	} // setThumbWidth()

	/**
	 * Set the value of [thumb_height] column.
	 * 
	 * @param      int $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setThumbHeight($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->thumb_height !== $v) {
			$this->thumb_height = $v;
			$this->modifiedColumns[] = PhotoPeer::THUMB_HEIGHT;
		}

		return $this;
	} // setThumbHeight()

	/**
	 * Set the value of [icon_width] column.
	 * 
	 * @param      int $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setIconWidth($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->icon_width !== $v) {
			$this->icon_width = $v;
			$this->modifiedColumns[] = PhotoPeer::ICON_WIDTH;
		}

		return $this;
	} // setIconWidth()

	/**
	 * Set the value of [icon_height] column.
	 * 
	 * @param      int $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setIconHeight($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->icon_height !== $v) {
			$this->icon_height = $v;
			$this->modifiedColumns[] = PhotoPeer::ICON_HEIGHT;
		}

		return $this;
	} // setIconHeight()

	/**
	 * Set the value of [wander_width] column.
	 * 
	 * @param      int $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setWanderWidth($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->wander_width !== $v) {
			$this->wander_width = $v;
			$this->modifiedColumns[] = PhotoPeer::WANDER_WIDTH;
		}

		return $this;
	} // setWanderWidth()

	/**
	 * Set the value of [wander_height] column.
	 * 
	 * @param      int $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setWanderHeight($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->wander_height !== $v) {
			$this->wander_height = $v;
			$this->modifiedColumns[] = PhotoPeer::WANDER_HEIGHT;
		}

		return $this;
	} // setWanderHeight()

	/**
	 * Set the value of [slide_width] column.
	 * 
	 * @param      int $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setSlideWidth($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->slide_width !== $v) {
			$this->slide_width = $v;
			$this->modifiedColumns[] = PhotoPeer::SLIDE_WIDTH;
		}

		return $this;
	} // setSlideWidth()

	/**
	 * Set the value of [slide_height] column.
	 * 
	 * @param      int $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setSlideHeight($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->slide_height !== $v) {
			$this->slide_height = $v;
			$this->modifiedColumns[] = PhotoPeer::SLIDE_HEIGHT;
		}

		return $this;
	} // setSlideHeight()

	/**
	 * Set the value of [longitude] column.
	 * 
	 * @param      double $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setLongitude($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->longitude !== $v) {
			$this->longitude = $v;
			$this->modifiedColumns[] = PhotoPeer::LONGITUDE;
		}

		return $this;
	} // setLongitude()

	/**
	 * Set the value of [latitude] column.
	 * 
	 * @param      double $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setLatitude($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->latitude !== $v) {
			$this->latitude = $v;
			$this->modifiedColumns[] = PhotoPeer::LATITUDE;
		}

		return $this;
	} // setLatitude()

	/**
	 * Sets the value of [shot_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setShotDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->shot_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->shot_date !== null && $tmpDt = new DateTime($this->shot_date)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->shot_date = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PhotoPeer::SHOT_DATE;
			}
		} // if either are not null

		return $this;
	} // setShotDate()

	/**
	 * Sets the value of [open_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setOpenDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->open_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->open_date !== null && $tmpDt = new DateTime($this->open_date)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->open_date = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = PhotoPeer::OPEN_DATE;
			}
		} // if either are not null

		return $this;
	} // setOpenDate()

	/**
	 * Sets the value of [modified_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setModifiedDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->modified_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->modified_date !== null && $tmpDt = new DateTime($this->modified_date)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->modified_date = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PhotoPeer::MODIFIED_DATE;
			}
		} // if either are not null

		return $this;
	} // setModifiedDate()

	/**
	 * Sets the value of [metamodified_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setMetamodifiedDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->metamodified_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->metamodified_date !== null && $tmpDt = new DateTime($this->metamodified_date)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->metamodified_date = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PhotoPeer::METAMODIFIED_DATE;
			}
		} // if either are not null

		return $this;
	} // setMetamodifiedDate()

	/**
	 * Sets the value of [filemtime] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setFilemtime($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->filemtime !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->filemtime !== null && $tmpDt = new DateTime($this->filemtime)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->filemtime = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PhotoPeer::FILEMTIME;
			}
		} // if either are not null

		return $this;
	} // setFilemtime()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PhotoPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PhotoPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->title = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->filename = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->comment = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->width = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->height = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->thumb_width = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->thumb_height = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->icon_width = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->icon_height = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->wander_width = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->wander_height = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->slide_width = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->slide_height = ($row[$startcol + 13] !== null) ? (int) $row[$startcol + 13] : null;
			$this->longitude = ($row[$startcol + 14] !== null) ? (double) $row[$startcol + 14] : null;
			$this->latitude = ($row[$startcol + 15] !== null) ? (double) $row[$startcol + 15] : null;
			$this->shot_date = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->open_date = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->modified_date = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->metamodified_date = ($row[$startcol + 19] !== null) ? (string) $row[$startcol + 19] : null;
			$this->filemtime = ($row[$startcol + 20] !== null) ? (string) $row[$startcol + 20] : null;
			$this->created_at = ($row[$startcol + 21] !== null) ? (string) $row[$startcol + 21] : null;
			$this->updated_at = ($row[$startcol + 22] !== null) ? (string) $row[$startcol + 22] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 23; // 23 = PhotoPeer::NUM_COLUMNS - PhotoPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Photo object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PhotoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PhotoPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PhotoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePhoto:delete:pre') as $callable)
			{
			  if ($ret = call_user_func($callable, $this, $con))
			  {
			    return;
			  }
			}

			if ($ret) {
				PhotoPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePhoto:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PhotoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePhoto:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(PhotoPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(PhotoPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePhoto:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				$con->commit();
				PhotoPeer::addInstanceToPool($this);
				return $affectedRows;
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = PhotoPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PhotoPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += PhotoPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = PhotoPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PhotoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getTitle();
				break;
			case 2:
				return $this->getFilename();
				break;
			case 3:
				return $this->getComment();
				break;
			case 4:
				return $this->getWidth();
				break;
			case 5:
				return $this->getHeight();
				break;
			case 6:
				return $this->getThumbWidth();
				break;
			case 7:
				return $this->getThumbHeight();
				break;
			case 8:
				return $this->getIconWidth();
				break;
			case 9:
				return $this->getIconHeight();
				break;
			case 10:
				return $this->getWanderWidth();
				break;
			case 11:
				return $this->getWanderHeight();
				break;
			case 12:
				return $this->getSlideWidth();
				break;
			case 13:
				return $this->getSlideHeight();
				break;
			case 14:
				return $this->getLongitude();
				break;
			case 15:
				return $this->getLatitude();
				break;
			case 16:
				return $this->getShotDate();
				break;
			case 17:
				return $this->getOpenDate();
				break;
			case 18:
				return $this->getModifiedDate();
				break;
			case 19:
				return $this->getMetamodifiedDate();
				break;
			case 20:
				return $this->getFilemtime();
				break;
			case 21:
				return $this->getCreatedAt();
				break;
			case 22:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PhotoPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getTitle(),
			$keys[2] => $this->getFilename(),
			$keys[3] => $this->getComment(),
			$keys[4] => $this->getWidth(),
			$keys[5] => $this->getHeight(),
			$keys[6] => $this->getThumbWidth(),
			$keys[7] => $this->getThumbHeight(),
			$keys[8] => $this->getIconWidth(),
			$keys[9] => $this->getIconHeight(),
			$keys[10] => $this->getWanderWidth(),
			$keys[11] => $this->getWanderHeight(),
			$keys[12] => $this->getSlideWidth(),
			$keys[13] => $this->getSlideHeight(),
			$keys[14] => $this->getLongitude(),
			$keys[15] => $this->getLatitude(),
			$keys[16] => $this->getShotDate(),
			$keys[17] => $this->getOpenDate(),
			$keys[18] => $this->getModifiedDate(),
			$keys[19] => $this->getMetamodifiedDate(),
			$keys[20] => $this->getFilemtime(),
			$keys[21] => $this->getCreatedAt(),
			$keys[22] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PhotoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setTitle($value);
				break;
			case 2:
				$this->setFilename($value);
				break;
			case 3:
				$this->setComment($value);
				break;
			case 4:
				$this->setWidth($value);
				break;
			case 5:
				$this->setHeight($value);
				break;
			case 6:
				$this->setThumbWidth($value);
				break;
			case 7:
				$this->setThumbHeight($value);
				break;
			case 8:
				$this->setIconWidth($value);
				break;
			case 9:
				$this->setIconHeight($value);
				break;
			case 10:
				$this->setWanderWidth($value);
				break;
			case 11:
				$this->setWanderHeight($value);
				break;
			case 12:
				$this->setSlideWidth($value);
				break;
			case 13:
				$this->setSlideHeight($value);
				break;
			case 14:
				$this->setLongitude($value);
				break;
			case 15:
				$this->setLatitude($value);
				break;
			case 16:
				$this->setShotDate($value);
				break;
			case 17:
				$this->setOpenDate($value);
				break;
			case 18:
				$this->setModifiedDate($value);
				break;
			case 19:
				$this->setMetamodifiedDate($value);
				break;
			case 20:
				$this->setFilemtime($value);
				break;
			case 21:
				$this->setCreatedAt($value);
				break;
			case 22:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PhotoPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setTitle($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setFilename($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setComment($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setWidth($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setHeight($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setThumbWidth($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setThumbHeight($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setIconWidth($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setIconHeight($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setWanderWidth($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setWanderHeight($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setSlideWidth($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setSlideHeight($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setLongitude($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setLatitude($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setShotDate($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setOpenDate($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setModifiedDate($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setMetamodifiedDate($arr[$keys[19]]);
		if (array_key_exists($keys[20], $arr)) $this->setFilemtime($arr[$keys[20]]);
		if (array_key_exists($keys[21], $arr)) $this->setCreatedAt($arr[$keys[21]]);
		if (array_key_exists($keys[22], $arr)) $this->setUpdatedAt($arr[$keys[22]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PhotoPeer::DATABASE_NAME);

		if ($this->isColumnModified(PhotoPeer::ID)) $criteria->add(PhotoPeer::ID, $this->id);
		if ($this->isColumnModified(PhotoPeer::TITLE)) $criteria->add(PhotoPeer::TITLE, $this->title);
		if ($this->isColumnModified(PhotoPeer::FILENAME)) $criteria->add(PhotoPeer::FILENAME, $this->filename);
		if ($this->isColumnModified(PhotoPeer::COMMENT)) $criteria->add(PhotoPeer::COMMENT, $this->comment);
		if ($this->isColumnModified(PhotoPeer::WIDTH)) $criteria->add(PhotoPeer::WIDTH, $this->width);
		if ($this->isColumnModified(PhotoPeer::HEIGHT)) $criteria->add(PhotoPeer::HEIGHT, $this->height);
		if ($this->isColumnModified(PhotoPeer::THUMB_WIDTH)) $criteria->add(PhotoPeer::THUMB_WIDTH, $this->thumb_width);
		if ($this->isColumnModified(PhotoPeer::THUMB_HEIGHT)) $criteria->add(PhotoPeer::THUMB_HEIGHT, $this->thumb_height);
		if ($this->isColumnModified(PhotoPeer::ICON_WIDTH)) $criteria->add(PhotoPeer::ICON_WIDTH, $this->icon_width);
		if ($this->isColumnModified(PhotoPeer::ICON_HEIGHT)) $criteria->add(PhotoPeer::ICON_HEIGHT, $this->icon_height);
		if ($this->isColumnModified(PhotoPeer::WANDER_WIDTH)) $criteria->add(PhotoPeer::WANDER_WIDTH, $this->wander_width);
		if ($this->isColumnModified(PhotoPeer::WANDER_HEIGHT)) $criteria->add(PhotoPeer::WANDER_HEIGHT, $this->wander_height);
		if ($this->isColumnModified(PhotoPeer::SLIDE_WIDTH)) $criteria->add(PhotoPeer::SLIDE_WIDTH, $this->slide_width);
		if ($this->isColumnModified(PhotoPeer::SLIDE_HEIGHT)) $criteria->add(PhotoPeer::SLIDE_HEIGHT, $this->slide_height);
		if ($this->isColumnModified(PhotoPeer::LONGITUDE)) $criteria->add(PhotoPeer::LONGITUDE, $this->longitude);
		if ($this->isColumnModified(PhotoPeer::LATITUDE)) $criteria->add(PhotoPeer::LATITUDE, $this->latitude);
		if ($this->isColumnModified(PhotoPeer::SHOT_DATE)) $criteria->add(PhotoPeer::SHOT_DATE, $this->shot_date);
		if ($this->isColumnModified(PhotoPeer::OPEN_DATE)) $criteria->add(PhotoPeer::OPEN_DATE, $this->open_date);
		if ($this->isColumnModified(PhotoPeer::MODIFIED_DATE)) $criteria->add(PhotoPeer::MODIFIED_DATE, $this->modified_date);
		if ($this->isColumnModified(PhotoPeer::METAMODIFIED_DATE)) $criteria->add(PhotoPeer::METAMODIFIED_DATE, $this->metamodified_date);
		if ($this->isColumnModified(PhotoPeer::FILEMTIME)) $criteria->add(PhotoPeer::FILEMTIME, $this->filemtime);
		if ($this->isColumnModified(PhotoPeer::CREATED_AT)) $criteria->add(PhotoPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(PhotoPeer::UPDATED_AT)) $criteria->add(PhotoPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PhotoPeer::DATABASE_NAME);

		$criteria->add(PhotoPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Photo (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setTitle($this->title);

		$copyObj->setFilename($this->filename);

		$copyObj->setComment($this->comment);

		$copyObj->setWidth($this->width);

		$copyObj->setHeight($this->height);

		$copyObj->setThumbWidth($this->thumb_width);

		$copyObj->setThumbHeight($this->thumb_height);

		$copyObj->setIconWidth($this->icon_width);

		$copyObj->setIconHeight($this->icon_height);

		$copyObj->setWanderWidth($this->wander_width);

		$copyObj->setWanderHeight($this->wander_height);

		$copyObj->setSlideWidth($this->slide_width);

		$copyObj->setSlideHeight($this->slide_height);

		$copyObj->setLongitude($this->longitude);

		$copyObj->setLatitude($this->latitude);

		$copyObj->setShotDate($this->shot_date);

		$copyObj->setOpenDate($this->open_date);

		$copyObj->setModifiedDate($this->modified_date);

		$copyObj->setMetamodifiedDate($this->metamodified_date);

		$copyObj->setFilemtime($this->filemtime);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Photo Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PhotoPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PhotoPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BasePhoto:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BasePhoto::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BasePhoto
