<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/01/04 07:54:19

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:host=localhost;dbname=okinawa',
  'username' => 'okinawa',
  'password' => 'okinawa',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
