<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/01/04 08:45:31
sfConfig::add(array(
  'mod_photo_enabled' => true,
  'mod_photo_view_class' => 'sfPHP',
  'mod_photo_is_internal' => false,
));
