# default values
all:
  photo:
    url: '/photo/'
    width: 800
    height: 533
  wander:
    url: '/wander400/'
    width: 400
    height: 267
  slide:
    url: '/320/'
    width: 320
    height: 213
  thumb:
    url: '/thumb/'
    width: 100
    height: 67
  icon:
    url: '/icon/'
    width: 30
    height: 20
  path:
    upload: '/home/photo/'
    photo: '/home/okinawa_storage/photo/'
    wander: '/home/okinawa_storage/wander400/'
    slide: '/home/okinawa_storage/320/'
    thumb: '/home/okinawa_storage/thumb/'
    icon: '/home/okinawa_storage/icon/'
    shadow: '/home/okinawa/data/'
    topbg: '/home/okinawa_storage/topbg/'
    profile: '/home/okinawa_storage/text/profile.txt'
    toptext: '/home/okinawa_storage/text/top.txt'
  quality:
    photo: 80
    wander: 80
    slide: 75
    thumb: 65
    icon: 50
  map:
    key: 'ABQIAAAAjGShGyfNDuPu7erceIQP9BQzJaWPQ7XczUdbKaT67LclnHpQXBSKFcleTvTzwTOuIpCJEfMJEpk-Nw'
 
    