placeSuccess:
  has_layout: off
withinmapSuccess:
  has_layout: off
photoinmapSuccess:
  has_layout: off
keywordphotosSuccess:
  has_layout: off
keywordpageSuccess:
  has_layout: off
blogphotoSuccess:
  has_layout: off
xmlreadSuccess:
  has_layout: off
wanderupdateSuccess:
  has_layout: off
mapthumbnailSuccess:
  has_layout: off
addlinkSuccess:
  has_layout: off
ajaxgetphotoSuccess:
  has_layout: off
ajaxthumblistSuccess:
  has_layout: off


default:
  http_metas:
    content-type: text/html

  metas:
    title:        '沖縄写真旅行'
    robots:       index, follow
    description:  '沖縄の写真を多数掲載。'
    keywords:     '沖縄,写真,写真集'
    language:     ja

  stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout
