<title>沖縄写真旅行 - 知り合いリンク</title>
<meta name="robots" content="index,follow" />
</head>
<body>
<?php
// auto-generated by sfPropelCrud
// date: 2007/04/06 17:17:58

use_helper('okinawa');
?>
<div class="topframe">
</div>
<h1 class="title">知り合いリンク&nbsp;&nbsp;<span style="font-size:14px;">by <a href="/">沖縄写真旅行</a></span></h1>
<div class="comment"></div>
<table>
<tr><td width="400" align="center" valign="middle">
  <a href="/show/1647"><?php img_photo($photo); ?></a>
</td>
<td valign="top" align="left">
<?php
foreach ($category as $cat) {
  print '<div class="categorytitle">' . $cat->getTitle() . '</div>';
  print '<div class="linktitle">';
  foreach ($linklist as $link) {
    if ($link->getCategoryId() == $cat->getId()) {
      print '<a href="' . $link->getUrl() . '">' . $link->getTitle() . '</a><br />';
    }
  }
  print '</div>';
}


?>
<br />

</td></tr></table>

