<?php

$FONT_FAMILY = array(
'"みかちゃん", "MS P明朝", "Osaka", "VL ゴシック"',
'"あくあフォント", "平成明朝体", "HG正楷書体-PRO", "さざなみゴシック"',
'"雑字", "ヒラギノ丸ゴ Pro W3", "HGP行書体", "さざなみ明朝"',
'"ヒラギノ明朝", "HGS創英角", "VL Pゴシック"',
);
$FONT_SIZE = array(
'13px', '15px', '17px', '19px', '21px', '23px',
);

?>
<title>沖縄写真旅行 - ノート</title>
<meta name="robots" content="index,follow" />
<script type="text/javascript" src="/js/prototype.js"></script>
<script type="text/javascript">

function showWrite() {
  var buff;
  buff = '<form acti';
  buff += 'on="<?php echo url_for('photo/notewrite'); ?>" method="post">';
  buff += '<div style="text-align:right"><textarea name="comment" rows=2 cols=32></textarea><br>';
  buff += '<input type="text" name="name" size=12><br>';
  buff += '<input type="submit" value="ここに書く"></div>';
  buff += '</form>';
  
  $('writearea').innerHTML = buff;
}

</script>
</head>
<body class="note">
<?php
// auto-generated by sfPropelCrud
// date: 2007/04/06 17:17:58

use_helper('okinawa');
?>
<div class="notebody">
お気軽にどうぞ。<br />
<br />
<?php

for ($i = 0; $i < sizeof($notes); $i++) {
  $n = $notes[$i];
  
  print '<div style="font-size:' . $FONT_SIZE[$n->getFontSize()] . '; font-family:' . $FONT_FAMILY[$n->getFontFamily()] . ';">';
  print '<a name="n' . $n->getId() . '"></a>';
  print preg_replace('/\r\n|\r|\n/', '<br>', $n->getContent());
  print '</div><div style="text-align:right; font-family:' . $FONT_FAMILY[$n->getFontFamily()] . ';">' . $n->getName();
  //print '<br>' . ((int)substr($n->getWriteDate(), 5, 2)) . '/' . ((int)substr($n->getWriteDate(), 8, 2));
  print '</div>';
}

?>
<br>
<div id="writearea">
<div style="text-align:right;color:#7777ff;cursor:pointer;" onClick="showWrite()">ここに書く</div>
</div>

</div>