<title>沖縄写真旅行 - 知り合いリンク</title>
<meta name="robots" content="index,follow" />
</head>
<body>
<?php
// auto-generated by sfPropelCrud
// date: 2007/04/06 17:17:58

use_helper('okinawa');
?>
<div class="topframe">
</div>
<h1 class="title">相互リンク&nbsp;&nbsp;<span style="font-size:14px;">by <a href="/">沖縄写真旅行</a></span></h1>
<div class="comment"></div>
<table>
<tr><td width="400" align="center" valign="middle">
  <a href="/show/2520"><?php img_photo($photo); ?></a>
</td>
<td valign="top" align="left">
<?php
foreach ($list as $record) {
  print '<div class="linktitle">';
  print $record->getLinkstr();
  print '</div>';
}


?>
</td></tr></table>

