<title><?php echo $photo->getTitle(); ?></title>
<meta name="description" content="<?php echo preg_replace('/[\r\n]/', '', $photo->getComment()); ?>" />
    <meta name="robots" content="index,follow" />
</head>
<body>
<?php
// auto-generated by sfPropelCrud
// date: 2007/04/06 17:17:58

use_helper('okinawa');
?>
<div class="topframe">
</div>
<h1 class="title"><?php
echo $photo->getTitle();
echo '<span style="font-size:14px;">';
if ($todaywindow) {
  echo '&nbsp;&nbsp;';
  echo link_to('ブログパーツ「沖縄の窓」', 'photo/blogparts');
}

?>&nbsp;&nbsp;by <a href="/">沖縄写真旅行</a></span></h1>
<div class="comment"><?php echo $sf_data->getRaw('photo')->getComment(); ?></div>
<table class="mainphoto">
<tr><td width="810" align="center" valign="middle">
  <?php img_photo($photo); ?>
<p class="date">撮影日時 <?php shot_date($photo); ?> <?php
if ($photo->getLongitude() && $photo->getLatitude()) {
  echo link_to('場所(Map)', 'photo/map?zoom=17&longitude=' . str_replace('.', '_', $photo->getLongitude()) . '&latitude=' . str_replace('.', '_', $photo->getLatitude()) . '&photoid=' . $photo->getId());
}
?></p>
</td>
<td valign="top" align="left">
<div class="right">
<h3 class="sub">キーワード</h3>
<?php related_keywords($photo); ?>
<h3 class="sub">関連写真</h3>
<?php related_thumbnail($photo, $keywordid); ?>
</div>
</td></tr></table>

