<?php include_title() ?>

</head>
<body>
<?php
// auto-generated by sfPropelCrud
// date: 2007/04/06 17:17:58
?>
<?php use_helper('Object') ?>
<?php use_helper('Form') ?>
<div class="tool">
<div class="box">
<h2 class="boxtitle">画像をアップロード</h2>
<br />
<?php echo form_tag('carte/carteupload', array('enctype' => 'multipart/form-data')) ?>
<?php echo input_file_tag('cartefile'); ?><br />
<?php echo submit_tag('アップロード') ?>
</form>
</div>

<div class="box">
<h2 class="boxtitle">アップロード済み</h2>
<br />
現在　<?php echo $count; ?>枚



</div>

