<?php


/**
 * Skeleton subclass for performing query and update operations on the 'top_photo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Mon Jan  4 02:03:27 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TopPeer extends BaseTopPeer {

} // TopPeer
