 <?php include_title() ?>

</head>
<body>
<?php
// auto-generated by sfPropelCrud
// date: 2007/04/06 17:17:58
?>
<?php use_helper('okinawa'); ?>
<h1>ブログパーツ用写真</h1>
<br />
<div style="font-size:16px;color:red;"><?php echo $message; ?></div>
<div style="font-size:14px;">
選考基準<br />
- 縦横比が標準のもの（縦：横＝２：３）<br />
- 沖縄に行きたくなるもの<br />
- 嫌がる人がいないもの（ブログに張られた画像は設置者以外の客も見る）<br />
<br />
日替わりでこのストックからランダムで選ばれる。<br />
ストックが尽きてたら「樹木、緑」からランダムで選ぶ。<br />
</div>
<br />
<form action="<? echo url_for('tool/blogphotoinput'); ?>" method="post">
ID <input type="text" name="photoid"><br />
<input type="submit" value="追加">
</form>

<table cellpadding="2">
<thead>
<tr>
  <th>操作</th>
  <th>画像</th>
  <th>ID</th>
  <th>使用日時</th>
</tr>
</thead>
<tbody>
<?php foreach ($blogphotos as $blogphoto): ?>
<tr>
      <td><?php echo link_to('削除', 'tool/blogphotodelete?id=' . $blogphoto->getPhotoId()); ?></td>
      <td><?php
      foreach ($photos as $photo) {
        if ($photo->getId() == $blogphoto->getPhotoId()) {
          echo okinawaUtil::getThumbnailTagSlim($photo);
          break;
        }
      }
      ?></td>
      <td width="32"><?php echo $blogphoto->getPhotoId(); ?></td>
      <td width="80"><?php echo $blogphoto->getUseDate() ?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
