<?php include_title() ?>

</head>
<body>
<?php
// auto-generated by sfPropelCrud
// date: 2007/04/06 17:17:58
?>
<?php use_helper('Object') ?>
<?php use_helper('Form') ?>
<div class="tool">

<h1 class="title">写真のアップロード</h1>

<div class="box">
<h2 class="boxtitle">STEP1 画像ファイルをCyberDuckでアップロードする</h2>
<br />
CyberDuckというソフトをダウンロードしてインストールしてください。<br />
<br />
<a href="http://cyberduck.ch/">CyberDuck公式サイト</a><br />
<br />
下記のように設定してください。
<table>
<tr>
  <th>プロトコル</th><td>SFTP</td>
</tr>
<tr>
  <th>接続先</th><td>photo-okinawa.com</td>
</tr>
<tr>
  <th>ID</th><td>photo</td>
</tr>
<tr>
  <th>PASSWORD</th><td>wk93hfg</td>
</tr>
</table>
プロトコルは、FTPとSFTPから選択できるはずです。SFTPはSSHと表示されることもあります。もしSFTPがなくてSCPがあれば、SCPを選択してください。<br />
接続先は、「ホスト」とか「サーバ」と表示されることがあります。<br />
その他のオプションは特に重要ではありません。<br />
<br />
初めて接続に成功したら、接続の設定情報を保存しましょう。<br />
<br />
/home/photo/というディレクトリが表示されます。<br />
全ての画像をそのまま放り込んでください。ファイル名はIMGPとかのままで。<br />
アップロードには多大な時間がかかります。どうしようもありません。<br />
STEP2を行うまでは、サイトには反映されません。<br />
</div>

<div class="box">
<h2 class="boxtitle">STEP2 AlbumData.xmlをこのページで読み込む</h2>
<br />
<?php echo form_tag('tool/xmlread', array('enctype' => 'multipart/form-data')) ?>
<?php echo input_file_tag('xml'); ?><br />
<?php echo submit_tag('アップロード') ?>
</form>
ファイルの読み込みに成功した時点で、画像、コメント、タグがサイトに反映されます。<br />
</div>

<div class="box">
<h2 class="boxtitle">STEP3 管理リストで確認</h2>
<br />
<?php echo link_to('管理リスト', 'tool/list'); ?>でコメントやタグの漏れを確認できます。<br />
<br />
現在　<?php echo $count; ?>枚<br>
公開済み　<?php echo $opencount; ?>枚<br>

</div>

