<?php include_title() ?>

</head>
<body>
<?php
// auto-generated by sfPropelCrud
// date: 2007/04/06 17:17:58
?>
<?php use_helper('okinawa'); ?>
<h1>キーワードリスト</h1>
<br />
キーワード数 : <?php echo sizeof($keywords); ?><br />
<br />
<table cellpadding="2">
<thead>
<tr>
  <th>表示優先度</th>
  <th>ID</th>
  <th>操作</th>
  <th>キーワード</th>
  <th>英語名</th>
  <th width="640">説明</th>
  <th>表示</th>
</tr>
</thead>
<tbody>
<?php foreach ($keywords as $keyword): ?>
<tr>
      <td><?php echo $keyword->getOrderPriority(); ?></td>
      <td><?php echo $keyword->getId(); ?></td>
      <td><?php echo link_to('編集', 'tool/keywordedit?id=' . $keyword->getId()); ?></td>
      <td><?php echo $keyword->getTitle(); ?></td>
      <?php
      if (strlen($keyword->getEnglishtitle())) {
        echo '<td>' . $keyword->getEnglishtitle() . '</td>';
      }
      else {
        echo '<td style="background-color:#ffe0e0">&nbsp;</td>';
      }
      ?>
      <?php
      if (strlen($keyword->getDescription())) {
        echo '<td>' . $keyword->getDescription() . '</td>';
      }
      else {
        echo '<td style="background-color:#ffe0e0">&nbsp;</td>';
      }
      ?>
      <td><?php echo link_to($keyword->getTitle(), 'photo/keyword?title=' . $keyword->getTitle()); ?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
