<?php include_title() ?>

</head>
<body>
<?php
// auto-generated by sfPropelCrud
// date: 2007/04/06 17:17:58
?>
<?php use_helper('Object') ?>
<?php use_helper('okinawa'); ?>
<div class="edit">
<?php echo form_tag('tool/linkupdate') ?>
<h1>リンク編集</h1>
<table>
<tbody>
<tr>
  <th>URL</th>
  <td><input type="text" name="url" value="<?php echo $obj->getUrl(); ?>" size=50></td>
</tr>
<tr>
  <th>タイトル</th>
  <td><input type="text" name="title" value="<?php echo $obj->getTitle(); ?>" size=40></td>
</tr>
<!--
<tr>
  <th>説明文</th>
  <td><input type="text" name="description" value="<?php echo $obj->getDescription(); ?>" size=60></td>
</tr>
-->
<tr>
  <th>カテゴリ</th>
  <td><select name="category"><?php
foreach ($category as $one) {
  echo '<option value="' . $one->getId() . '"';
  if ($obj->getCategoryId() == $one->getId()) {
    echo " selected";
  }
  echo '>' . $one->getTitle() . '</option>';
}
?></select></td>
</tr>
</tbody>
</table>
<br />
<input type="hidden" name="id" value="<?php echo $obj->getId(); ?>">
<br />
<?php echo submit_tag('更新') ?>
</form>
</div>