<?php include_title() ?>

</head>
<body>
<?php
// auto-generated by sfPropelCrud
// date: 2007/04/06 17:17:58
?>
<?php use_helper('okinawa'); ?>
<h1>リンクカテゴリ追加</h1>
<br />
<form action="<?php echo url_for('tool/linkcategoryadd'); ?>" method="post">
カテゴリ名 <input type="text" name="categorytitle" size=30><br />
表示優先度 <input type="text" name="categorypriority" size=5><br />
<input type="submit" value="追加">
</form>
<br />
<br />
<br />
<h1>登録済みのリンクカテゴリ</h1>
<table cellpadding="2">
<thead>
<tr>
  <th>表示優先度</th>
  <th>ID</th>
  <th width=120>操作</th>
  <th>名称</th>
</tr>
</thead>
<tbody>
<?php foreach ($category as $one): ?>
<tr>
      <td><?php echo $one->getOrderPriority(); ?></td>
      <td><?php echo $one->getId(); ?></td>
      <td><?php echo link_to('編集', 'tool/linkcategoryedit?id=' . $one->getId()); ?>
      &nbsp;&nbsp;
      <?php echo link_to('削除', 'tool/linkcategorydelete?id=' . $one->getId()); ?></td>
      <td><?php echo $one->getTitle(); ?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<br />
<br />
<br />
<h1>リンク追加</h1>
<br />
<form action="<?php echo url_for('tool/linkadd'); ?>" method="post">
カテゴリ <select name="linkcategory"><?php
foreach ($category as $one) {
  echo '<option value="' . $one->getId() . '">' . $one->getTitle() . '</option>';
}
?></select><br />
URL <input type="text" name="url" size=50><br />
タイトル <input type="text" name="linktitle" size=30><br />
<!--説明文 <input type="text" name="linkdescription" size=50><br />-->
<input type="submit" value="追加">
</form>
<br />
<br />
<br />
<h1>登録済みのリンク</h1>
<table cellpadding="2">
<thead>
<tr>
  <th>ID</th>
  <th width=120>操作</th>
  <th>URL</th>
  <th>名称</th>
<!--  <th>説明文</th> -->
  <th>カテゴリ</th>
</tr>
</thead>
<tbody>
<?php foreach ($linklist as $one): ?>
<tr>
      <td><?php echo $one->getId(); ?></td>
      <td><?php echo link_to('編集', 'tool/linkedit?id=' . $one->getId()); ?>
      &nbsp;&nbsp;
      <?php echo link_to('削除', 'tool/linkdelete?id=' . $one->getId()); ?></td>
      <td><?php echo $one->getUrl(); ?></td>
      <td><?php echo $one->getTitle(); ?></td>
<!--      <td><?php echo $one->getDescription(); ?></td> -->
      <td><?php echo $one->getCategoryId(); ?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
