<?php include_title() ?>

</head>
<body>
<?php
// auto-generated by sfPropelCrud
// date: 2007/04/06 17:17:58
?>
<?php use_helper('Object') ?>
<?php use_helper('okinawa'); ?>
<div class="edit">
<?php echo form_tag('tool/linkcategoryupdate') ?>
<h1>リンクカテゴリ編集</h1>
<table>
<tbody>
<tr>
  <th>表示優先度</th>
  <td><input type="text" name="priority" value="<?php echo $linkcategory->getOrderPriority(); ?>" size=5></td>
</tr>
<tr>
  <th>名称</th>
  <td><input type="text" name="title" value="<?php echo $linkcategory->getTitle(); ?>" size=40></td>
</tr>
</tbody>
</table>
<br />
<input type="hidden" name="id" value="<?php echo $linkcategory->getId(); ?>">
<br />
<?php echo submit_tag('更新') ?>
</form>
</div>