<?php include_title() ?>

</head>
<body>
<?php
// auto-generated by sfPropelCrud
// date: 2007/04/06 17:17:58
?>
<?php use_helper('Object') ?>
<?php use_helper('okinawa'); ?>
<div class="edit">
<?php echo form_tag('tool/topphotoupdate') ?>
<h1><?php echo $top->getId(); ?>時</h1>
<table>
<tbody>
<tr>
  <th>写真ID</th>
  <td><input type="text" name="photo_id" value="<?php echo $top->getPhotoId(); ?>" size=40></td>
</tr>
<tr>
  <th>テキストカラー</th>
  <td><input type="text" name="text_color" value="<?php echo $top->getTextColor(); ?>" size=40></td>
</tr>
<tr>
  <th>リンクカラー</th>
  <td><input type="text" name="link_color" value="<?php echo $top->getLinkColor(); ?>" size=40></td>
</tr>
</tbody>
</table>
<br />
<input type="hidden" name="id" value="<?php echo $top->getId(); ?>">
<br />
<?php echo submit_tag('更新') ?>
</form>
</div>