<?php include_title() ?>

</head>
<body>
<?php
// auto-generated by sfPropelCrud
// date: 2007/04/06 17:17:58
?>
<?php use_helper('okinawa'); ?>
<h1>壁紙用写真</h1>
<br />
<div style="font-size:14px;">
選考基準<br />
- 沖縄とわかるもの、沖縄を感じるもの、沖縄と説明されて納得できるもの（壁紙は、オフィスなどで使用される際にはTシャツ並のアイデンティティ主張のアイテムと考えてよく、美しければ良いわけではない）<br />
<br />
</div>
<br />
<form action="<? echo url_for('tool/wallinput'); ?>" method="post">
ID <input type="text" name="photoid"><br />
<input type="submit" value="追加">
</form>

<table cellpadding="2">
<thead>
<tr>
  <th>操作</th>
  <th>画像</th>
  <th>ID</th>
</tr>
</thead>
<tbody>
<?php foreach ($photos as $photo): ?>
<tr>
      <td><?php echo link_to('削除', 'tool/walldelete?id=' . $photo->getId()); ?></td>
      <td><?php
	  echo '<a href="' . wallpaper_url($photo, 1024, 768) . '">1024x768</a>';
	  echo '&nbsp;';
	  echo '<a href="' . wallpaper_url($photo, 1280, 800) . '">1280x800</a>';
	  echo '&nbsp;';
	  echo '<a href="' . wallpaper_url($photo, 1280, 1024) . '">1280x1024</a>';
	  echo '&nbsp;';
	  echo '<a href="' . wallpaper_url($photo, 1400, 1050) . '">1400x1050</a>';
	  ?>
      </td>
      <td width="320"><?php echo $photo->getTitle(); ?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
