<?php print '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<?php include_http_metas() ?>
<meta http-equiv="content-style-type" content="text/css" />
<meta http-equiv="content-script-type" content="text/javascript" />
<?php include_title() ?>

</head>
<body>
<?php
// auto-generated by sfPropelCrud
// date: 2007/04/06 17:17:58

use_helper('okinawa');

$cnt = sizeof($list);
$okcnt = 0;
for ($i = 0; $i < $cnt; $i++) {
  $result = okinawaUtil::procAlbum($list[$i], $tagHash);
  print "[" . ($i + 1) . "/" . "$cnt] " . $result . "<br />";
  if ($result == 'ok') {
    $okcnt++;
  }
  if ($okcnt >= 50) {
    print '処理対象の量が多いため全てを処理していません。再度操作を行ってください。<br />';
    break;
  }
}

?>
<br />
<br />
<?php echo link_to('戻る', 'tool/input'); ?><br />
<br />
</body>
</html>
